[package]
name = "sanctaphraxx"
version = "0.1.1"
authors = ["Ciekce"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrayvec = "0.7.4"
